### ISSUE TITLE
Doesn't display UTF-8 characters

### ISSUE THREAD

**Issue by ghost** [myles-parfeniuk/esp32_SH1122#1]
When connecting a Cyrillic font, Russian symbols are not displayed. For example: Привет Мир!.
An empty string without any characters.

**Comment by myles-parfeniuk** [comment]
This issue stemmed from me forgetting to implement utf-8 decoding when I ported U8G2's font system.

Thank you for pointing out the oversight. I have merged some changes from my development branch that should correct the issue. To utilize them simply call load_font_utf8 instead of load_font if you plan to use utf-8 encoded strings.

I have only tested 3 Cyrillic fonts (sh1122_font_8x13_t_cyrillic, sh1122_font_10x20_t_cyrillic, sh1122_font_inr27_t_cyrillic) so I cannot guarantee all are working, please open another issue if you have any other problems.

The README.md was also updated with an example of how to use utf-8 strings, but here's an example here for your convenience:

```cpp
#include <stdio.h>
#include "SH1122Oled.hpp"
#include "fonts/sh1122_font_8x13_t_cyrillic.hpp"
#include "fonts/sh1122_font_10x20_t_cyrillic.hpp"
#include "fonts/sh1122_font_inr27_t_cyrillic.hpp"

extern "C" void app_main(void)
{
    SH1122Oled oled; // using default initialization

    // load font in utf-8 mode decoding
    SH1122Oled::load_font_utf8(sh1122_font_inr27_t_cyrillic);

    while (1)
    {

        oled.clear_buffer(); // clear buffer of previous frame before drawing

        // draw the string
        oled.draw_string(5, 15, SH1122Oled::PixelIntensity::level_15, "Привет Мир!");
        oled.update_screen(); // send the current buffer to the screen

        vTaskDelay(50 / portTICK_PERIOD_MS);
    }
}
```

**Comment by ghost** [comment]
Thank you very much! I will try these changes. And I will definitely write to you about the results. Happy New Year! I wish you all the best.

**Comment by ghost** [comment]
**Super!** Everything works great!
You can also use **symbol fonts**.
I like your project. 
**Thanks!**
```
#include "main.hpp"

extern "C" void app_main(void)
{
    SH1122Oled oled; // using default initialization

    while (1)
    {

        oled.clear_buffer(); // clear buffer of previous frame before drawing

        // draw the string
        SH1122Oled::load_font_utf8(sh1122_font_cu12_t_cyrillic);
        oled.draw_string(104, 32, SH1122Oled::PixelIntensity::level_15, "Привет Мир!");
        SH1122Oled::load_font(sh1122_font_unifont_t_symbols);
        oled.draw_glyph(80, 32, SH1122Oled::PixelIntensity::level_15, 0x2603);
        oled.draw_glyph(196, 32, SH1122Oled::PixelIntensity::level_15, 0x2603);
        oled.update_screen(); // send the current buffer to the screen

        vTaskDelay(50 / portTICK_PERIOD_MS);
    }
}
```

![oled](https://github.com/user-attachments/assets/b479d8f5-61c7-4ef4-ac09-7e187ed59ce1)

**Comment by myles-parfeniuk** [comment]
My pleasure, happy you're enjoying it. I saw you liked some of my other esp-idf repos like ButtonDriver and DataControl, I have to warn you those are old and crusty, bad implementations, I need to rework them at some point.

Thank you for putting in some test work. 

Merry christmas and happy new year :)

**Comment by ghost** [comment]
Merry christmas and happy new year :)
